### ISSUE TITLE
LaTeX support

### ISSUE THREAD

**Issue by mfernandes61** [elixir-europe-training/ELIXIR-TrP-LessonTemplate-MkDocs#25]
Hi - Am I correct in thinking that LaTex is not supported in this MkDocs template?
I can't get formulaee to render with single $ or double $

Found this reference https://gist.github.com/josemazo/36af7bb9c58b92c684bbd431f6c68ce9 
but these are not in medics.yml

**Comment by GeertvanGeest** [comment]
Hi Mark,

MathJax and KaTex are supported: https://squidfunk.github.io/mkdocs-material/reference/math/. Make sure to adjust `mkdocs.yml` to import the required extensions. 

It should be relatively straightforward to implement by following the docs in the link. Let me know if it doesn't work as it should.

Cheers!

**Comment by mfernandes61** [comment]
Thanks - got it working
