### ISSUE TITLE
render page fails with latest version of mkdocs mkdocs_material-9.5.3

### ISSUE THREAD

**Issue by abotzki** [elixir-europe-training/ELIXIR-TrP-LessonTemplate-MkDocs#28]
@GeertvanGeest When creating a new repo based on this template, a new version 9.5.3 of mkdoc material framework is installed.

Unfortunately, the current mkdocs.yml configuration triggers an error with the bibtex plugin.
https://github.com/elixir-europe-training/ELIXIR-TrP-FAIR-Material-By-Design/actions/runs/7358376042/job/20031539341

I could work around it temporarily by commenting 2 lines in the mkdocs.yml file - see [e927b07](https://github.com/elixir-europe-training/ELIXIR-TrP-FAIR-Material-By-Design/commit/e927b07d79cd716dcfe7b2a9a0aff0c4d4da42d1) 

As far as I saw in the older version 9.4.14, there was a warning that an API call will be deprecated: https://github.com/elixir-europe-training/ELIXIR-TrP-TeSS/actions/runs/7117131929/job/19377166113 - see line 226ff
In versions before (so 9.4.9 or so from other successful rendering tasks of other repos, I did not see this info).

**Comment by abotzki** [comment]
I just found this thread: https://bitbucket.org/pybtex-devs/pybtex/issues/169/replace-pkg_resources-with
the suggested solution is to install `setuptools` - I'll try this.

**Comment by abotzki** [comment]
Seems to be fixed: see https://github.com/elixir-europe-training/ELIXIR-TrP-FAIR-Material-By-Design/actions/runs/7359230979

**Comment by GeertvanGeest** [comment]
Thanks @abotzki! I added this to the action and generally updated them. 
I just realized that `.github/render_page.yml` is not part of the template sync. So, I updated that. I'll trigger the template sync manually now and see whether the action will be updated though a PR on your side.

**Comment by GeertvanGeest** [comment]
I tried to integrate the .github folder into the template sync, but it requires setting up a PAT, and I think that is a bit too much to ask for most users for now. Therefore, you can take over https://github.com/elixir-europe-training/ELIXIR-TrP-LessonTemplate-MkDocs/blob/main/.github/workflows/render_page.yml (I also updated the action versions). I'll send PRs in the coming days to other repositories.

**Comment by abotzki** [comment]
Hi, @GeertvanGeest 

thanks a lot. 

I've already copied the new version of render_page.yml for three repos: 
https://github.com/elixir-europe-training/ELIXIR-TrP-ContainersPython-CodeRep
https://github.com/elixir-europe-training/ELIXIR-TrP-TeSS
https://github.com/elixir-europe-training/ELIXIR-TrP-FAIR-Material-By-Design

**Comment by GeertvanGeest** [comment]
Thanks Alex. To prevent similar issues in the future, I amended the page build workflow to use a `requirements.txt` file. In that way the dependencies are part of the template sync. I've sent an issue to all of the repositories that use the template. It describes the required steps.
