### ISSUE TITLE
Versioning of the template

### ISSUE THREAD

**Issue by mihai-sysbio** [elixir-europe-training/ELIXIR-TrP-LessonTemplate-MkDocs#3]
Thinking of the long term compatibility of the template, how is versioning of the lesson template envisioned to be handled?

**Comment by GeertvanGeest** [comment]
If there's a template that is 'production-ready' (should be soon), I'd say we start by using version tags. Other than that there's no vision. Happy to hear suggestions!

**Comment by GeertvanGeest** [comment]
Using `mike` is pretty powerful; we use it all the time for SIB courses (e.g. https://sib-swiss.github.io/single-cell-training/2023.3/). However, I never got to it to write an action that runs after a git tag (= a gh release) is given and pushes a new version with `mike`. Would be nice to have one.

**Comment by GeertvanGeest** [comment]
An example of an action is referenced here: https://github.com/jimporter/mike/issues/79

**Comment by mihai-sysbio** [comment]
Actually, my initial point was about how to manage new release of the template repo in connection with the already-developed lessons. I guess a GH Action is the way to go, but that would have to be set up with a [schedule](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule), since the template might update even if the lesson doesn't.

**Comment by joseale2310** [comment]
I believe we have another issue regarding this? #13

**Comment by mihai-sysbio** [comment]
It certainly looks that way; my suggestion would be to close one of them.

**Comment by GeertvanGeest** [comment]
Closing this issue, add versioning with `mike` as new issue in #18
