### ISSUE TITLE
update README

### ISSUE THREAD

**Issue by elinkronander** [elixir-europe-training/ELIXIR-TrP-LessonTemplate-MkDocs#5]
The README file needs to be updated to describe this modified template.
It could contain:

- short description of the purpose of template
- short description of the technical details (mk-docs, material theme, gh actions, gh-pages, ie how does a commit to main branch propagates to the gh-pages branch etc.)
- link to the [instructions](https://elixir-europe-training.github.io/ELIXIR-TrP-LessonTemplateInstructions-MkDocs/) 
- information on who to contact if someone wants a repo under the elixir-europe-training namespace
- information on how to get help in general (maybe a slack channel?)
- examples of material where this template has been used

**Comment by ac812** [comment]
Readme updated
