### ISSUE TITLE
rename the template

### ISSUE THREAD

**Issue by elinkronander** [elixir-europe-training/ELIXIR-TrP-LessonTemplate-MkDocs#6]
It was agreed with the ExCos that the template should be named ELIXIR-TrP-LessonTemplate-MkDocs

**Comment by ac812** [comment]
@GeertvanGeest  I do not have access to settings. Is it possible to give me admin access please?

**Comment by GeertvanGeest** [comment]
Done. I think the website address will change after the next push.
